# Generated by Django 5.2.6 on 2025-09-08 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('imei', models.CharField(blank=True, max_length=30)),
                ('numero_serie', models.CharField(blank=True, max_length=30)),
                ('accesorios', models.TextField(blank=True)),
                ('estado_visual', models.TextField(blank=True)),
                ('falla_declarada', models.TextField()),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('en_garantia', models.BooleanField(default=False)),
                ('fuera_garantia_por_uso', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.cliente')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes.marca')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes.tipoequipo')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ingresado', 'Ingresado'), ('revision', 'En revisión'), ('presupuestado', 'Presupuestado'), ('reparado', 'Reparado'), ('no_reparable', 'No Reparable'), ('espera_repuesto', 'En espera de repuesto'), ('demorado', 'Demorado'), ('retirado', 'Retirado')], default='ingresado', max_length=20)),
                ('diagnostico_tecnico', models.TextField(blank=True)),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.equipo')),
            ],
        ),
    ]
