# Generated by Django 5.2.6 on 2025-09-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_cliente_ciudad_cliente_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, default='Sin ciudad', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, default='Sin dirección', max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, default='sin_email@ejemplo.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, default='Sin observaciones'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(blank=True, default='Sin provincia', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, default='Sin teléfono', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_alternativo',
            field=models.CharField(blank=True, default='Sin alternativo', max_length=20),
        ),
    ]
